# Server Port
server:
  port: 8080

# DB Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin123
    username: postgres
    url: jdbc:postgresql://localhost:5432/db_cambodia_accessory

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true

# JPA configuration